import fs from 'fs';
import path from 'path';
import { getTheme } from './themes/index.js';

export class MonumentGenerator {
  constructor(options = {}) {
    this.theme = options.theme || process.env.THEME || 'default';
  }

  generate(analysisResult, outputDir = './output', options = {}) {
    const themeName = options.theme || this.theme;
    const theme = getTheme(themeName);

    const jsonPath = path.join(outputDir, 'monument.json');
    fs.writeFileSync(jsonPath, JSON.stringify(analysisResult, null, 2), 'utf-8');

    const htmlPath = path.join(outputDir, 'monument.html');
    const html = this._renderHTML(analysisResult, theme);
    fs.writeFileSync(htmlPath, html, 'utf-8');

    return { jsonPath, htmlPath };
  }

  _renderHTML(data, theme) {
    const { epitaph, trajectory, relationships, keywords, stats, meta } = data;

    const wordCloudHTML = this._renderWordCloud(stats?.wordCloud);
    const sentimentHTML = this._renderSentiment(stats?.sentiment);
    const scheduleHTML = this._renderSchedule(stats?.schedule);
    const relationshipsHTML = this._renderRelationshipGraph(stats?.relationships);

    const yearBlocks = (trajectory || []).map(t => `
      <div class="year-block">
        <div class="year-label">${t.year}</div>
        <div class="year-content">${this._escapeHtml(t.summary)}</div>
      </div>
    `).join('');

    const relBlocks = (relationships || []).map(r => `
      <div class="rel-item">
        <div class="rel-name">${this._escapeHtml(r.name)}</div>
        <div class="rel-role">${this._escapeHtml(r.role)}</div>
        <div class="rel-bar"><div class="rel-bar-fill" style="width:${(r.intimacy * 100).toFixed(0)}%"></div></div>
      </div>
    `).join('');

    const keywordBlocks = (keywords || []).map(k => `
      <div class="kw-year">
        <div class="kw-year-label">${k.year}</div>
        <div class="kw-tags">${(k.words || []).map(w => `<span class="kw-tag">${this._escapeHtml(w)}</span>`).join('')}</div>
      </div>
    `).join('');

    const startDate = meta?.timeRange?.start ? new Date(meta.timeRange.start * 1000).toLocaleDateString('zh-CN') : '';
    const endDate = meta?.timeRange?.end ? new Date(meta.timeRange.end * 1000).toLocaleDateString('zh-CN') : '';

    if (theme.render && typeof theme.render === 'function') {
      return theme.render(data);
    }

    return `<!-- Generated by 一个人的纪念碑 -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>一个人的纪念碑</title>
<style>${theme.css}</style>
</head>
<body>
<div class="container">

  <div class="hero">
    <h1 class="hero-title">一个人的纪念碑</h1>
    <div class="hero-subtitle">A Person's Monument</div>
    <div class="hero-meta">
      ${startDate} &mdash; ${endDate} | ${stats?.totalMessages || 0} 条消息 | ${(meta?.platforms || []).join(' / ')}
    </div>
  </div>

  <div class="epitaph-section">
    <div class="section-title">纪念碑</div>
    <div class="epitaph-text">${this._escapeHtml(epitaph || '')}</div>
  </div>

  ${trajectory && trajectory.length > 0 ? `
  <div class="section">
    <div class="section-title">人生轨迹</div>
    ${yearBlocks}
  </div>` : ''}

  ${relationships && relationships.length > 0 ? `
  <div class="section">
    <div class="section-title">重要的人</div>
    ${relBlocks}
  </div>` : ''}

  ${keywords && keywords.length > 0 ? `
  <div class="section">
    <div class="section-title">年度关键词</div>
    ${keywordBlocks}
  </div>` : ''}

  <div class="section">
    <div class="section-title">数据印记</div>
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-num">${stats?.totalMessages || 0}</div>
        <div class="stat-label">总消息数</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${stats?.totalContacts || 0}</div>
        <div class="stat-label">联系人数</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${stats?.avgMessagesPerDay || 0}</div>
        <div class="stat-label">日均消息</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${((stats?.selfMessageRatio || 0) * 100).toFixed(0)}%</div>
        <div class="stat-label">自己发言比例</div>
      </div>
    </div>
  </div>

  ${wordCloudHTML}

  ${sentimentHTML}

  ${scheduleHTML}

  ${relationshipsHTML}

  <div class="footer">
    <div class="footer-quote">"人永远都值得被记得和记住。"</div>
    <div class="footer-info">
      一个人的纪念碑 &middot; 生成于 ${new Date().toLocaleString('zh-CN')}<br>
      原始数据已焚毁 &middot; 仅此留存
    </div>
  </div>

</div>
</body>
</html>`;
  }

  _renderWordCloud(wordCloud) {
    if (!wordCloud || wordCloud.length === 0) return '';

    const maxCount = Math.max(...wordCloud.map(w => w.count), 1);
    const minSize = 12;
    const maxSize = 36;

    const items = wordCloud.slice(0, 50).map((w) => {
      const ratio = w.count / maxCount;
      const size = minSize + ratio * (maxSize - minSize);
      const opacity = 0.5 + ratio * 0.5;
      return `<span class="word-cloud-item" style="font-size:${size.toFixed(1)}px; opacity:${opacity.toFixed(2)}">${this._escapeHtml(w.word)}</span>`;
    }).join('');

    return `
  <div class="section">
    <div class="section-title">词云</div>
    <div class="word-cloud-container">
      ${items}
    </div>
  </div>`;
  }

  _renderSentiment(sentiment) {
    if (!sentiment) return '';

    const { positiveCount, negativeCount, neutralCount, byYear } = sentiment;

    const yearBars = (byYear || []).map(y => {
      const height = Math.abs(y.score) * 100 + 10;
      const type = y.score >= 0 ? 'positive' : 'negative';
      return `
        <div class="sentiment-bar-wrap">
          <div class="sentiment-bar ${type}" style="height:${height.toFixed(0)}%"></div>
          <div class="sentiment-bar-label">${y.year}</div>
        </div>`;
    }).join('');

    return `
  <div class="section">
    <div class="section-title">情感分析</div>
    <div class="sentiment-overview">
      <div class="sentiment-card positive">
        <div class="sentiment-num">${positiveCount}</div>
        <div class="sentiment-label">正面消息</div>
      </div>
      <div class="sentiment-card neutral">
        <div class="sentiment-num">${neutralCount}</div>
        <div class="sentiment-label">中性消息</div>
      </div>
      <div class="sentiment-card negative">
        <div class="sentiment-num">${negativeCount}</div>
        <div class="sentiment-label">负面消息</div>
      </div>
    </div>
    ${byYear && byYear.length > 0 ? `
    <div class="sentiment-chart">
      <div class="sentiment-bars">
        ${yearBars}
      </div>
    </div>` : ''}
  </div>`;
  }

  _renderSchedule(schedule) {
    if (!schedule || !schedule.hourlyDistribution) return '';

    const { hourlyDistribution, isNightOwl, mostActiveHour, lateNightRatio } = schedule;
    const maxCount = Math.max(...Object.values(hourlyDistribution), 1);

    let bars = '';
    for (let i = 0; i < 24; i++) {
      const count = hourlyDistribution[i] || 0;
      const height = (count / maxCount) * 100 || 2;
      const isNight = (i >= 23 || i <= 5);
      const isActive = i === mostActiveHour;
      let barClass = 'schedule-bar';
      if (isNight) barClass += ' night';
      if (isActive) barClass += ' active';
      const showLabel = i % 3 === 0;
      bars += `
        <div class="schedule-bar-wrap">
          <div class="${barClass}" style="height:${height.toFixed(0)}%" title="${i}时: ${count}条"></div>
          ${showLabel ? `<div class="schedule-bar-label">${i}时</div>` : '<div class="schedule-bar-label">&nbsp;</div>'}
        </div>`;
    }

    return `
  <div class="section">
    <div class="section-title">作息分布</div>
    <div class="schedule-chart">
      <div class="schedule-bars">
        ${bars}
      </div>
      <div class="schedule-info">
        <div class="schedule-info-item">
          <span class="schedule-info-label">最活跃时段</span>
          <span class="schedule-info-value">${mostActiveHour}:00</span>
        </div>
        <div class="schedule-info-item">
          <span class="schedule-info-label">深夜消息占比</span>
          <span class="schedule-info-value">${(lateNightRatio * 100).toFixed(1)}%</span>
        </div>
        <div class="schedule-info-item">
          <span class="schedule-info-label">是否夜猫子</span>
          <span class="schedule-info-value">${isNightOwl ? '是' : '否'}</span>
        </div>
        <div class="schedule-info-item">
          <span class="schedule-info-label">统计时段</span>
          <span class="schedule-info-value">24小时</span>
        </div>
      </div>
    </div>
  </div>`;
  }

  _renderRelationshipGraph(relationships) {
    if (!relationships || !relationships.nodes || relationships.nodes.length === 0) return '';

    const graphData = JSON.stringify(relationships).replace(/</g, '\\u003c').replace(/'/g, '&#39;');

    const legendItems = (relationships.categories || []).map((cat, i) => {
      const colors = ['var(--accent)', '#e87878', 'var(--accent2)', 'var(--muted)', '#6b5b8a'];
      const color = colors[i % colors.length];
      return `
        <div class="relationship-legend-item">
          <span class="relationship-legend-dot" style="background:${color}"></span>
          <span>${this._escapeHtml(cat.name)}</span>
        </div>`;
    }).join('');

    return `
  <div class="section">
    <div class="section-title">关系图谱</div>
    <div id="relationship-graph" class="relationship-graph" data-graph='${graphData}'>
      <div class="relationship-placeholder">关系图谱加载中...</div>
    </div>
    <div class="relationship-legend">
      ${legendItems}
    </div>
  </div>`;
  }

  _escapeHtml(text) {
    if (!text) return '';
    const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
    return String(text).replace(/[&<>"']/g, m => map[m]);
  }
}
