/**
 * 纪念碑生成器 - 将 AI 分析结果渲染为 HTML 纪念页
 *
 * 输出:
 * 1. monument.json - 结构化数据（可上传到纪念碑谷）
 * 2. monument.html - 自包含的 HTML 纪念页（可离线保存）
 */

import fs from 'fs';
import path from 'path';

export class MonumentGenerator {
  /**
   * 生成纪念碑
   * @param {Object} analysisResult - AI 分析结果
   * @param {string} outputDir - 输出目录
   * @returns {Object} { jsonPath, htmlPath }
   */
  generate(analysisResult, outputDir = './output') {
    // 生成 monument.json
    const jsonPath = path.join(outputDir, 'monument.json');
    fs.writeFileSync(jsonPath, JSON.stringify(analysisResult, null, 2), 'utf-8');

    // 生成 monument.html
    const htmlPath = path.join(outputDir, 'monument.html');
    const html = this._renderHTML(analysisResult);
    fs.writeFileSync(htmlPath, html, 'utf-8');

    return { jsonPath, htmlPath };
  }

  /**
   * 渲染 HTML 纪念页
   */
  _renderHTML(data) {
    const { epitaph, trajectory, relationships, keywords, stats, meta } = data;

    const yearBlocks = (trajectory || []).map(t => `
      <div class="year-block">
        <div class="year-label">${t.year}</div>
        <div class="year-content">${this._escapeHtml(t.summary)}</div>
      </div>
    `).join('');

    const relBlocks = (relationships || []).map(r => `
      <div class="rel-item">
        <div class="rel-name">${this._escapeHtml(r.name)}</div>
        <div class="rel-role">${this._escapeHtml(r.role)}</div>
        <div class="rel-bar"><div class="rel-bar-fill" style="width:${(r.intimacy * 100).toFixed(0)}%"></div></div>
      </div>
    `).join('');

    const keywordBlocks = (keywords || []).map(k => `
      <div class="kw-year">
        <div class="kw-year-label">${k.year}</div>
        <div class="kw-tags">${(k.words || []).map(w => `<span class="kw-tag">${this._escapeHtml(w)}</span>`).join('')}</div>
      </div>
    `).join('');

    const startDate = meta?.timeRange?.start ? new Date(meta.timeRange.start * 1000).toLocaleDateString('zh-CN') : '';
    const endDate = meta?.timeRange?.end ? new Date(meta.timeRange.end * 1000).toLocaleDateString('zh-CN') : '';

    return `<!-- Generated by 一个人的纪念碑 -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>一个人的纪念碑</title>
<style>
:root {
  --bg: #0a0a0f; --bg2: #15151f; --bg3: #1e1e2e;
  --ink: #e8e4d8; --muted: #8a8580; --rule: #2a2a3a;
  --accent: #d4a574; --accent2: #5fb8a8;
  --glow: rgba(212,165,116,0.15);
}
* { margin:0; padding:0; box-sizing:border-box; }
body {
  background: var(--bg); color: var(--ink);
  font-family: 'Georgia', 'Noto Serif SC', serif;
  line-height: 1.9; -webkit-font-smoothing: antialiased;
}
body::before {
  content:''; position:fixed; top:0;left:0;right:0;bottom:0;
  background: radial-gradient(ellipse at 50% 0%, var(--glow) 0%, transparent 60%);
  pointer-events:none; z-index:0;
}
.container { max-width:720px; margin:0 auto; padding:0 1.5rem; position:relative; z-index:1; }

/* Hero */
.hero { text-align:center; padding:6rem 0 4rem; }
.hero-title {
  font-size:2.5rem; font-weight:400; color:var(--ink);
  letter-spacing:0.1em; margin-bottom:0.5rem;
}
.hero-subtitle { font-size:0.85rem; color:var(--accent2); letter-spacing:0.3em; text-transform:uppercase; }
.hero-meta { margin-top:2rem; font-size:0.8rem; color:var(--muted); font-family:monospace; }

/* Epitaph */
.epitaph-section { padding:3rem 0; }
.epitaph-text {
  font-size:1.1rem; color:var(--ink); line-height:2.1;
  white-space:pre-wrap; text-align:justify;
  padding:2.5rem; background:var(--bg2); border-radius:8px;
  border-left:3px solid var(--accent);
  position:relative; overflow:hidden;
}
.epitaph-text::before {
  content:'"'; position:absolute; top:-1rem; left:1rem;
  font-size:5rem; color:var(--accent); opacity:0.1;
}

/* Section */
.section { padding:3rem 0; }
.section-title {
  font-size:1.3rem; color:var(--accent); margin-bottom:1.5rem;
  font-weight:400; letter-spacing:0.05em;
  display:flex; align-items:center; gap:0.75rem;
}
.section-title::after { content:''; flex:1; height:1px; background:linear-gradient(90deg,var(--rule),transparent); }

/* Trajectory */
.year-block { display:flex; gap:1.5rem; margin-bottom:1.5rem; align-items:flex-start; }
.year-label {
  font-family:monospace; font-size:1.2rem; color:var(--accent);
  min-width:60px; font-weight:700;
}
.year-content { color:var(--muted); font-size:0.95rem; flex:1; }

/* Relationships */
.rel-item { margin-bottom:1.25rem; }
.rel-name { font-size:0.95rem; color:var(--ink); }
.rel-role { font-size:0.8rem; color:var(--muted); margin-bottom:0.3rem; }
.rel-bar { height:3px; background:var(--bg2); border-radius:2px; overflow:hidden; }
.rel-bar-fill { height:100%; background:linear-gradient(90deg,var(--accent),var(--accent2)); }

/* Keywords */
.kw-year { margin-bottom:1.5rem; }
.kw-year-label { font-family:monospace; color:var(--accent2); font-size:0.9rem; margin-bottom:0.5rem; }
.kw-tags { display:flex; flex-wrap:wrap; gap:0.5rem; }
.kw-tag {
  font-size:0.85rem; color:var(--ink); background:var(--bg2);
  padding:4px 12px; border-radius:3px; border:1px solid var(--rule);
}

/* Stats */
.stats-grid { display:grid; grid-template-columns:repeat(2,1fr); gap:1rem; }
.stat-card { background:var(--bg2); padding:1.5rem; border-radius:6px; text-align:center; border:1px solid var(--rule); }
.stat-num { font-size:1.8rem; color:var(--accent); font-family:monospace; }
.stat-label { font-size:0.75rem; color:var(--muted); margin-top:0.3rem; }

/* Footer */
.footer { text-align:center; padding:3rem 0; border-top:1px solid var(--rule); margin-top:2rem; }
.footer-quote { font-style:italic; color:var(--accent); font-size:0.95rem; margin-bottom:0.5rem; }
.footer-info { font-size:0.75rem; color:var(--muted); font-family:monospace; }

@media (max-width:600px) {
  .hero-title { font-size:1.8rem; }
  .epitaph-text { font-size:1rem; padding:1.5rem; }
  .stats-grid { grid-template-columns:1fr; }
  .year-block { flex-direction:column; gap:0.3rem; }
}
</style>
</head>
<body>
<div class="container">

  <div class="hero">
    <h1 class="hero-title">一个人的纪念碑</h1>
    <div class="hero-subtitle">A Person's Monument</div>
    <div class="hero-meta">
      ${startDate} &mdash; ${endDate} | ${stats?.totalMessages || 0} 条消息 | ${(meta?.platforms || []).join(' / ')}
    </div>
  </div>

  <div class="epitaph-section">
    <div class="section-title">纪念碑</div>
    <div class="epitaph-text">${this._escapeHtml(epitaph || '')}</div>
  </div>

  ${trajectory && trajectory.length > 0 ? `
  <div class="section">
    <div class="section-title">人生轨迹</div>
    ${yearBlocks}
  </div>` : ''}

  ${relationships && relationships.length > 0 ? `
  <div class="section">
    <div class="section-title">重要的人</div>
    ${relBlocks}
  </div>` : ''}

  ${keywords && keywords.length > 0 ? `
  <div class="section">
    <div class="section-title">年度关键词</div>
    ${keywordBlocks}
  </div>` : ''}

  <div class="section">
    <div class="section-title">数据印记</div>
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-num">${stats?.totalMessages || 0}</div>
        <div class="stat-label">总消息数</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${stats?.totalContacts || 0}</div>
        <div class="stat-label">联系人数</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${stats?.avgMessagesPerDay || 0}</div>
        <div class="stat-label">日均消息</div>
      </div>
      <div class="stat-card">
        <div class="stat-num">${((stats?.selfMessageRatio || 0) * 100).toFixed(0)}%</div>
        <div class="stat-label">自己发言比例</div>
      </div>
    </div>
  </div>

  <div class="footer">
    <div class="footer-quote">"人永远都值得被记得和记住。"</div>
    <div class="footer-info">
      一个人的纪念碑 &middot; 生成于 ${new Date().toLocaleString('zh-CN')}<br>
      原始数据已焚毁 &middot; 仅此留存
    </div>
  </div>

</div>
</body>
</html>`;
  }

  /**
   * HTML 转义
   */
  _escapeHtml(text) {
    if (!text) return '';
    const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
    return String(text).replace(/[&<>"']/g, m => map[m]);
  }
}
